source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Holarchy_Example', :exclusive => true do
  pod "Holarchy", :path => "../"
end

target 'Holarchy_Tests', :exclusive => true do
  pod "Holarchy", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
