source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

target 'Holarchy_Example' do
  pod "Holarchy", :path => "../"
  pod 'Masonry'
end

target 'Holarchy_Tests' do
  pod "Holarchy", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'Masonry'
end
